/* orconfig.h for Windows -- This file is *not* generated by autoconf.
 * Instead, it has to be hand-edited to keep Win32 happy.
 */

// #define __USE_GNU
// #include <ucontext.h>

/* tor requires system headers; suppress the Bitcoin no-system-includes guard */
#ifdef __NO_SYSTEM_INCLUDES
#undef __NO_SYSTEM_INCLUDES
#endif

#ifdef _WIN32
/* Minimum Windows version: Vista (0x0600) required by tor's winthreads */
#undef WINVER
#undef _WIN32_WINNT
#define WINVER 0x0600
#define _WIN32_WINNT 0x0600
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <io.h>
#include <process.h>
#include <sys/utime.h>
/* Include io.h for low-level I/O functions on Windows */
#include <io.h>
#endif

#include <openssl/opensslv.h>


/* # for 0.4.8.12 Approximate date when this software was released. (Updated
   when the version changes.) */
#define APPROX_RELEASE_DATE "2024-06-06"

/* tor's build directory */
#define BUILDDIR "tor-0.4.8.12"

/* Windows-only defines. */
#define CONFDIR ""

/* Enable directory authority module */
#define HAVE_MODULE_DIRAUTH 1
#define HAVE_MODULE_DIRCACHE 1
#define HAVE_MODULE_POW 1
#define HAVE_MODULE_RELAY 1

/* Define to 1 if you have the <arpa/inet.h> header file. */
#undef HAVE_ARPA_INET_H

/* Define to 1 if you have the `gettimeofday' function. */
#undef HAVE_GETTIMEOFDAY

/* Define to 1 if you have the <grp.h> header file. */
#undef HAVE_GRP_H

/* Define to 1 if you have the `inet_aton' function. */
#undef HAVE_INET_ATON

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <machine/limits.h> header file. */
#undef HAVE_MACHINE_LIMITS_H

/* Define to 1 if you have the <netdb.h> header file. */
#undef HAVE_NETDB_H

/* Define to 1 if you have the <netinet/in.h> header file. */
#undef HAVE_NETINET_IN_H

/* Define to 1 if you have the <poll.h> header file. */
#undef HAVE_POLL_H

/* Define to 1 if you have the <pwd.h> header file. */
#undef HAVE_PWD_H

#undef HAVE_SYS_MMAN_H

/* Define to 1 if you have the `socketpair' function. */
#undef HAVE_SOCKETPAIR

/* Define to 1 if the system has the type `ssize_t'. */
#define HAVE_SSIZE_T 1

/* Define to 1 if the system has the type `intptr_t'. */
// #define HAVE_INTPTR_T 1

/* Define to 1 if the system has the type `uintptr_t'. */
// #define HAVE_UINTPTR_T 1

/* Define to 1 if you have the `SSL_get_client_ciphers' function. */
/* #undef HAVE_SSL_GET_CLIENT_CIPHERS */
#if OPENSSL_VERSION_NUMBER > 0x1000ffffL
#define HAVE_SSL_GET_CLIENT_CIPHERS 1
#endif

/* Define to 1 if you have the `SSL_get_client_random' function. */
/* #undef HAVE_SSL_GET_CLIENT_RANDOM */
#if OPENSSL_VERSION_NUMBER > 0x1000ffffL
#define HAVE_SSL_GET_CLIENT_RANDOM 1
#endif

/* Define to 1 if you have the `SSL_get_server_random' function. */
/* #undef HAVE_SSL_GET_SERVER_RANDOM */
#if OPENSSL_VERSION_NUMBER > 0x1000ffffL
#define HAVE_SSL_GET_SERVER_RANDOM 1
#endif

/* Define to 1 if you have the `SSL_SESSION_get_master_key' function. */
/* #undef HAVE_SSL_SESSION_GET_MASTER_KEY */
#if OPENSSL_VERSION_NUMBER > 0x1000ffffL
#define HAVE_SSL_SESSION_GET_MASTER_KEY 1
#endif

/* MinGW provides these in <string.h> */
#define HAVE_STRCASECMP 1
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the `strptime' function. */
#undef HAVE_STRPTIME

/* Define to 1 if you have the <sys/fcntl.h> header file. */
#undef HAVE_SYS_FCNTL_H

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#undef HAVE_SYS_IOCTL_H

/* Windows has <io.h> for low-level I/O (write, _lseeki64, _chsize) */
#define HAVE_IO_H 1

/* Define to 1 if you have the <sys/limits.h> header file. */
#undef HAVE_SYS_LIMITS_H

/* Define to 1 if you have the <sys/poll.h> header file. */
#undef HAVE_SYS_POLL_H

/* Define to 1 if you have the <sys/socket.h> header file. */
#undef HAVE_SYS_SOCKET_H


/* Windows gets timeval from winsock2.h, not sys/time.h */
#undef HAVE_SYS_TIME_H
#undef HAVE_SYS_TIMEVAL_H
#define HAVE_WINSOCK2_H 1

/* Use ANSI Windows APIs, not Unicode, to match string literal types */
/* #undef UNICODE */
/* #undef _UNICODE */

#include <sys/utime.h>
#define utime _utime
#undef HAVE_UTIME_H
#define HAVE_SYS_UTIME_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
#undef HAVE_SYS_WAIT_H

/* Define to 1 if you have the `uname' function. */
#undef HAVE_UNAME

/* Define to 1 if you have the <unistd.h> header file. */
#undef HAVE_UNISTD_H

/* Define to 1 iff NULL is represented by a 0 in memory. */
#define NULL_REP_IS_ZERO_BYTES 1

/* Define to 1 iff memset(0) sets doubles to 0.0 */
#define DOUBLE_0_REP_IS_ZERO_BYTES 1

/* Package info */
#define PACKAGE "tor"
#define PACKAGE_NAME "tor"
#define PACKAGE_STRING "tor 0.4.8.12"
#define PACKAGE_TARNAME "tor"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "0.4.8.12"
#define PACKAGE_BUGREPORT ""
#define SRCDIR "."


/* Define to the version of this package. */
#undef PACKAGE_VERSION

/* The size of a `char', as computed by sizeof. */
#define SIZEOF_CHAR 1

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `int16_t', as computed by sizeof. */
#undef SIZEOF_INT16_T

/* The size of a `int32_t', as computed by sizeof. */
#undef SIZEOF_INT32_T

/* The size of a `int64_t', as computed by sizeof. */
#undef SIZEOF_INT64_T

/* The size of a `int8_t', as computed by sizeof. */
#undef SIZEOF_INT8_T


/* The size of `pid_t', as computed by sizeof. */
#define SIZEOF_PID_T 4

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* The size of a `uint16_t', as computed by sizeof. */
#undef SIZEOF_UINT16_T

/* The size of a `uint32_t', as computed by sizeof. */
#undef SIZEOF_UINT32_T

/* The size of a `uint64_t', as computed by sizeof. */
#undef SIZEOF_UINT64_T

/* The size of a `uint8_t', as computed by sizeof. */
#undef SIZEOF_UINT8_T

/* The size of a `void *', as computed by sizeof. */
#define SIZEOF_VOID_P 8

/* Define to 1 if you have the ANSI C header files. */
#if !defined(STDC_HEADERS_)
  #define STDC_HEADERS_
#endif

#define HAVE_EVENT_H 1

/* Version number of package */
#define VERSION "0.4.8.12"

/* Compiler/platform properties */
#define FLEXIBLE_ARRAY_MEMBER 0
#define RSHIFT_DOES_SIGN_EXTEND 1
#define USING_TWOS_COMPLEMENT 1
#define MALLOC_ZERO_WORKS 1
#define STDC_HEADERS 1
#define STDATOMIC_WORKS 1
#define HAVE_STDATOMIC_H 1

/* sizeof — Windows 64-bit via MinGW */
#define SIZEOF___INT64 8
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define SIZEOF_SIZE_T 8
#define SIZEOF_TIME_T 8
#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_SOCKLEN_T 4
#define SIZEOF_CELL_T 0
#define SIZEOF_SHA_CTX 96

/* Crypto */
#define ENABLE_OPENSSL 1
#define OPENSSL_SUPPRESS_DEPRECATED 1
#define HAVE_TLS_METHOD 1
#define HAVE_SSL_CIPHER_FIND 1
#define HAVE_SSL_CTX_SET_SECURITY_LEVEL 1
#define HAVE_ERR_LOAD_KDF_STRINGS 1
#define HAVE_EVP_PBE_SCRYPT 1
#define USE_CURVE25519_DONNA 1
#define CURVE25519_ENABLED 1
#define EQUIX_STATIC 1
#define HASHX_STATIC 1
#define HASHX_SIZE 8

/* Libevent */
#define HAVE_EVENT_BASE_LOOPEXIT 1
#define HAVE_EVENT_GET_METHOD 1
#define HAVE_EVENT_GET_VERSION 1
#define HAVE_EVENT_H 1
#define HAVE_EVENT_SET_LOG_CALLBACK 1
#define HAVE_EVDNS_BASE_GET_NAMESERVER_ADDR 1
#define HAVE_EVENT2_BUFFEREVENT_SSL_H 1
#define HAVE_EVUTIL_SECURE_RNG_ADD_BYTES 1
#define HAVE_EVUTIL_SECURE_RNG_SET_URANDOM_DEVICE_FILE 1

/* Standard headers available on MinGW */
#define HAVE_ASSERT_H 1
#define HAVE_CTYPE_H 1
#define HAVE_ERRNO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MEMORY_H 1
#define HAVE_SIGNAL_H 1
#define HAVE_SNPRINTF 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_TIME_H 1
#define HAVE_VSNPRINTF 1
#define HAVE_MACRO__func__ 1
#define HAVE_MACRO__FUNCTION__ 1

/* Windows socket/network */
#define HAVE_STRUCT_IN6_ADDR 1
#define HAVE_STRUCT_SOCKADDR_IN6 1
#define HAVE_STRUCT_TIMEVAL_TV_SEC 1
#define HAVE_GETADDRINFO 1

/* Windows-specific */
#define HAVE__VSCPRINTF 1
#define ENABLE_THREADS 1
#define ENUM_VALS_ARE_SIGNED 1
#define UNALIGNED_INT_ACCESS_OK 1
#define TIME_T_IS_SIGNED 1
#define SHARE_DATADIR ""
#define CONFIG_FLAGS ""

/* Available on MinGW */
#define HAVE_FTIME 1
#undef HAVE_STRLCAT
#undef HAVE_STRLCPY
#define HAVE_STRNLEN 1
#define HAVE_STRTOULL 1


#define HAVE_EVENT2_EVENT_H 1
#define HAVE_EVENT2_DNS_H 1

#ifndef STDOUT_FILENO
#define STDOUT_FILENO 1
#endif

#ifndef STDERR_FILENO
#define STDERR_FILENO 2
#endif


