# Copyright (c) 2009-2010 Satoshi Nakamoto
# Distributed under the MIT/X11 software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

# Build STATIC for this makefile (1=static, 0=not)
STATIC=0

# DEBUG=1

-include local-env-unix.mk

INCLUDEPATHS += \
 -I"$(CURDIR)" \
 -I"$(CURDIR)/leveldb/include" \
 -I"$(CURDIR)/leveldb/helpers" \
 -I"$(CURDIR)/ethash" \
 -I"$(CURDIR)/ethash/include" \
 -I"$(CURDIR)/ethash/lib" \
 -I"$(CURDIR)/json" \
 -I"$(CURDIR)/explore" \
 -I"$(CURDIR)/bip32" \
 -I"$(CURDIR)"/tor \
 -I"$(CURDIR)"/tor/adapter


DEBUGFLAGS = -g

xCFLAGS += $(INCLUDEPATHS) -std=gnu17 $(DEBUGFLAGS)

USE_UPNP := -
USE_IPV6 := -

LINK := $(CXX)
ARCH := $(shell uname -m)

# ---------------------------------------------------------------------------
# Per-configuration build directories
#
# Object files and the leveldb static libs are tagged with OS, CPU and build
# type so that two platforms sharing one checkout (a network mount, a VM bind
# mount) cannot overwrite each other's artifacts. Mixing them surfaces at link
# time as "file format not recognized", which is a confusing way to learn that
# obj/ held Mach-O and ELF objects at the same time.
#
# BUILD_TAG is composed the way the planned CMake daemon build will name its
# binary dirs, so obj/Linux-x86_64 here maps onto build/Linux-x86_64 there.
# OBJDIR and LEVELDB_OUT_DIR are both overridable on the command line, which
# is the make-side equivalent of `cmake -B <dir>`:
#
#     make -f makefile.unix OBJDIR=obj/experiment breakoutd
#
# Note that `clean` now removes only the current configuration's directory.
# ---------------------------------------------------------------------------
HOST_OS := $(shell uname -s)
ifdef DEBUG
    BUILD_SUFFIX := -debug
else
    BUILD_SUFFIX :=
endif
BUILD_TAG ?= $(HOST_OS)-$(ARCH)$(BUILD_SUFFIX)
OBJDIR ?= obj/$(BUILD_TAG)
LEVELDB_OUT_DIR ?= out-$(BUILD_TAG)
LEVELDB_OUT = leveldb/$(LEVELDB_OUT_DIR)
$(shell mkdir -p $(OBJDIR))

DEFS = -DBOOST_SPIRIT_THREADSAFE

incDEFS = $(addprefix -I, $(CURDIR) $(CURDIR)/$(OBJDIR) \
                          $(BOOST_INCLUDE_PATH) $(BDB_INCLUDE_PATH) \
                          $(OPENSSL_INCLUDE_PATH) $(EVENT_INCLUDE_PATH) \
                          $(ZLIB_INCLUDE_PATH) )
DEFS += $(incDEFS)
LIBS = $(addprefix -L, $(BOOST_LIB_PATH) $(BDB_LIB_PATH) \
                       $(OPENSSL_LIB_PATH) $(EVENT_LIB_PATH) \
                       $(ZLIB_LIB_PATH))

LMODE = dynamic
LMODE2 = dynamic
ifeq (${STATIC}, 1)
    LMODE = static
    ifeq (${STATIC}, all)
        LMODE2 = static
    endif
endif
LIBS += -Wl,-B$(LMODE)

LIBS += \
   $(BOOST_LIB_PATH)/libboost_atomic.a \
   $(BOOST_LIB_PATH)/libboost_chrono.a \
   $(BOOST_LIB_PATH)/libboost_filesystem.a \
   $(BOOST_LIB_PATH)/libboost_program_options.a \
   $(BOOST_LIB_PATH)/libboost_thread.a \
   $(BDB_LIB_PATH)/libdb_cxx.a \
   $(OPENSSL_LIB_PATH)/libssl.a \
   $(OPENSSL_LIB_PATH)/libcrypto.a \
   $(EVENT_LIB_PATH)/libevent.a \
   $(ZLIB_LIB_PATH)/libz.a

ifndef USE_UPNP
    override USE_UPNP = -
endif
ifneq (${USE_UPNP}, -)
    LIBS += -l miniupnpc
    DEFS += -DUSE_UPNP=$(USE_UPNP)
endif

ifneq (${USE_IPV6}, -)
	DEFS += -DUSE_IPV6=$(USE_IPV6)
endif

LIBS += \
   -l dl \
   -l pthread


# Hardening
# Make some classes of vulnerabilities unexploitable in case one is discovered.
#
    # This is a workaround for Ubuntu bug #691722, the default -fstack-protector causes
    # -fstack-protector-all to be ignored unless -fno-stack-protector is used first.
    # see: https://bugs.launchpad.net/ubuntu/+source/gcc-4.5/+bug/691722
    HARDENING = -fno-stack-protector

    # Stack Canaries
    # Put numbers at the beginning of each stack frame and check that they are the same.
    # If a stack buffer if overflowed, it writes over the canary number and then on return
    # when that number is checked, it won't be the same and the program will exit with
    # a "Stack smashing detected" error instead of being exploited.
    HARDENING += -fstack-protector-all -Wstack-protector

    # Make some important things such as the global offset table read only as soon as
    # the dynamic linker is finished building it. This will prevent overwriting of addresses
    # which would later be jumped to.
    LDHARDENING += -Wl,-z,relro -Wl,-z,now

    # Build position independent code to take advantage of Address Space Layout Randomization
    # offered by some kernels.
    # see doc/build-daemon.md for more information.
    ifdef PIE
        HARDENING += -fPIE
        LDHARDENING += -pie
    endif

    # -D_FORTIFY_SOURCE=2 does some checking for potentially exploitable code patterns in
    # the source such overflowing a statically defined buffer.
    HARDENING += -D_FORTIFY_SOURCE=2
#


ifdef DEBUG
    OPTIFLAGS = -O0
else
    OPTIFLAGS = -O2
endif


EXT_OPTIONS =
ifeq (${ARCH}, i686)
    EXT_OPTIONS = -msse2
endif


# CXXFLAGS can be specified on the make command line, so we use xCXXFLAGS that only
# adds some defaults in front. Unfortunately, CXXFLAGS=... $(CXXFLAGS) does not work.
xCXXFLAGS = $(OPTIFLAGS) $(EXT_OPTIONS) \
            -std=c++17 -pthread -Wall -Wextra -Wno-ignored-qualifiers \
            -Wformat -Wformat-security -Wno-unused-parameter \
            $(DEBUGFLAGS) $(DEFS) $(HARDENING) $(INCLUDEPATHS) $(CXXFLAGS)

# LDFLAGS can be specified on the make command line, so we use xLDFLAGS that only
# adds some defaults in front. Unfortunately, LDFLAGS=... $(LDFLAGS) does not work.
xLDFLAGS = $(LDHARDENING) $(LDFLAGS)


OBJS = \
    obj/colors.o \
    obj/json_spirit_reader.o \
    obj/json_spirit_value.o \
    obj/json_spirit_writer.o \
    obj/alert.o \
    obj/version.o \
    obj/checkpoints.o \
    obj/netbase.o \
    obj/addrman.o \
    obj/crypter.o \
    obj/hash.o \
    obj/key.o \
    obj/db.o \
    obj/init.o \
    obj/irc.o \
    obj/keystore.o \
    obj/miner.o \
    obj/main.o \
    obj/net.o \
    obj/protocol.o \
    obj/bitcoinrpc.o \
    obj/rpcdump.o \
    obj/rpcnet.o \
    obj/rpcmining.o \
    obj/rpcwallet.o \
    obj/rpcblockchain.o \
    obj/rpcrawtransaction.o \
    obj/script.o \
    obj/sync.o \
    obj/util.o \
    obj/wallet.o \
    obj/walletdb.o \
    obj/noui.o \
    obj/kernel.o \
    obj/pbkdf2.o \
    obj/scrypt.o \
    obj/smessage.o \
    obj/stealth.o \
    obj/txdb-leveldb.o \
    obj/exploredb-leveldb.o \
    obj/rpcexplore.o \
    obj/ExploreDestination.o \
    obj/ExploreInput.o \
    obj/ExploreOutput.o \
    obj/ExploreInOutLookup.o \
    obj/ExploreInOutList.o \
    obj/ExploreTx.o \
    obj/ExploreCardTransfer.o \
    obj/ExploreCardInfo.o \
    obj/InOutInfo.o \
    obj/AddrTxInfo.o \
    obj/AddrInOutInfo.o \
    obj/HDTxInfo.o \
    obj/explore.o \
    obj/hdkeys.o \
    obj/secp256k1_openssl.o \
    obj/keccak.o \
    obj/keccakf800.o \
    obj/keccakf1600.o \
    obj/progpow.o \
    obj/ethash.o \
    obj/managed.o \
    obj/primes.o
    
#     obj/keccak256.o \
#     obj/ethaddress.o

all: breakoutd


LIBS += $(CURDIR)/$(LEVELDB_OUT)/libleveldb.a $(CURDIR)/$(LEVELDB_OUT)/libmemenv.a
DEFS += $(addprefix -I,$(CURDIR)/leveldb/include)
DEFS += $(addprefix -I,$(CURDIR)/leveldb/helpers)
OBJS += obj/txdb-leveldb.o

# leveldb/out-static/libleveldb.a:
#	@echo "Building LevelDB in leveldb/ ..."; cd leveldb; make staticlibs; cd ..;
$(LEVELDB_OUT)/libleveldb.a:
	@echo "Building LevelDB in leveldb/ ($(LEVELDB_OUT_DIR)) ..."
	cd leveldb ; CXXFLAGS="${CXXFLAGS} -std=c++17" OUT_DIR=$(LEVELDB_OUT_DIR) make staticlibs; cd ..;

$(OBJDIR)/txdb-leveldb.o: $(LEVELDB_OUT)/libleveldb.a


# auto-generated dependencies:
-include $(OBJDIR)/*.P

$(OBJDIR)/build.h: FORCE
	/bin/sh ../share/genbuild.sh $(OBJDIR)/build.h
version.cpp: $(OBJDIR)/build.h
DEFS += -DHAVE_BUILD_INFO

include tor/tor-include.mk

# Retarget every object named by the lists above (this file and
# tor/tor-include.mk) into the per-configuration directory. Done here,
# once, so those lists stay plain "obj/foo.o" and need no maintenance.
OBJS := $(patsubst obj/%,$(OBJDIR)/%,$(OBJS))

$(OBJDIR)/%.o: %.cpp
	$(CXX) -c $(xCXXFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

$(OBJDIR)/%.o: %.c
	$(CC) -c $(incDEFS) $(xCFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

$(OBJDIR)/%.o: json/%.cpp
	$(CXX) -c $(xCXXFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

$(OBJDIR)/%.o: explore/%.cpp
	$(CXX) -c $(xCXXFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

$(OBJDIR)/%.o: bip32/%.cpp
	$(CXX) -c $(xCXXFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

$(OBJDIR)/%.o: ethash/lib/ethash/%.cpp
	$(CXX) -c $(xCXXFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

$(OBJDIR)/%.o: ethash/lib/ethash/%.c
	$(CC) -c $(incDEFS) $(xCFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

$(OBJDIR)/%.o: ethash/lib/keccak/%.c
	$(CC) -c $(incDEFS) $(xCFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	      -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	  rm -f $(@:%.o=%.d)

$(OBJDIR)/toradapter.o: tor/adapter/toradapter.cpp
	$(CXX) -c $(xCXXFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
            -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	rm -f $(@:%.o=%.d)

breakoutd: $(LEVELDB_OUT)/libleveldb.a \
              $(OBJS) $(OBJDIR)/toradapter.o
	$(CXX) $(xCXXFLAGS) -o $@ $(LIBPATHS) $^ $(xLDFLAGS) $(LIBS)

clean:
	-rm -f breakoutd
	-rm -rf $(OBJDIR)
	cd leveldb; make OUT_DIR=$(LEVELDB_OUT_DIR) clean

FORCE:
